# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1107, 830)
        self.media1 = QtWidgets.QWidget(Form)
        self.media1.setGeometry(QtCore.QRect(40, 30, 521, 381))
        self.media1.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.media1.setObjectName("media1")
        self.media2 = QtWidgets.QWidget(Form)
        self.media2.setGeometry(QtCore.QRect(580, 30, 521, 381))
        self.media2.setStyleSheet("background-color: rgb(255, 0, 4);")
        self.media2.setObjectName("media2")
        self.tongbu = QtWidgets.QPushButton(Form)
        self.tongbu.setGeometry(QtCore.QRect(480, 460, 93, 28))
        self.tongbu.setObjectName("tongbu")
        self.v1_slider = QtWidgets.QSlider(Form)
        self.v1_slider.setGeometry(QtCore.QRect(40, 420, 441, 31))
        self.v1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v1_slider.setObjectName("v1_slider")
        self.v2_slider = QtWidgets.QSlider(Form)
        self.v2_slider.setGeometry(QtCore.QRect(580, 420, 441, 31))
        self.v2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v2_slider.setObjectName("v2_slider")
        self.time1 = QtWidgets.QLabel(Form)
        self.time1.setGeometry(QtCore.QRect(490, 430, 72, 15))
        self.time1.setObjectName("time1")
        self.time2 = QtWidgets.QLabel(Form)
        self.time2.setGeometry(QtCore.QRect(1030, 430, 72, 15))
        self.time2.setObjectName("time2")
        self.v1_stop_bnt = QtWidgets.QPushButton(Form)
        self.v1_stop_bnt.setGeometry(QtCore.QRect(150, 462, 93, 28))
        self.v1_stop_bnt.setObjectName("v1_stop_bnt")
        self.v1_start_bnt = QtWidgets.QPushButton(Form)
        self.v1_start_bnt.setGeometry(QtCore.QRect(50, 462, 93, 28))
        self.v1_start_bnt.setObjectName("v1_start_bnt")
        self.v2_stop_bnt = QtWidgets.QPushButton(Form)
        self.v2_stop_bnt.setGeometry(QtCore.QRect(690, 462, 93, 28))
        self.v2_stop_bnt.setObjectName("v2_stop_bnt")
        self.v2_start_bnt = QtWidgets.QPushButton(Form)
        self.v2_start_bnt.setGeometry(QtCore.QRect(590, 462, 93, 28))
        self.v2_start_bnt.setObjectName("v2_start_bnt")
        self.final_start_bnt = QtWidgets.QPushButton(Form)
        self.final_start_bnt.setGeometry(QtCore.QRect(170, 460, 93, 28))
        self.final_start_bnt.setObjectName("final_start_bnt")
        self.final_stop_bnt = QtWidgets.QPushButton(Form)
        self.final_stop_bnt.setGeometry(QtCore.QRect(270, 460, 93, 28))
        self.final_stop_bnt.setObjectName("final_stop_bnt")
        self.final_slider = QtWidgets.QSlider(Form)
        self.final_slider.setGeometry(QtCore.QRect(180, 430, 771, 22))
        self.final_slider.setOrientation(QtCore.Qt.Horizontal)
        self.final_slider.setObjectName("final_slider")
        self.final_time = QtWidgets.QLabel(Form)
        self.final_time.setGeometry(QtCore.QRect(840, 460, 131, 16))
        self.final_time.setObjectName("final_time")
        self.bq_btn = QtWidgets.QPushButton(Form)
        self.bq_btn.setGeometry(QtCore.QRect(270, 500, 93, 28))
        self.bq_btn.setObjectName("bq_btn")
        self.time_list = QtWidgets.QListWidget(Form)
        self.time_list.setGeometry(QtCore.QRect(370, 540, 291, 261))
        self.time_list.setObjectName("time_list")
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setGeometry(QtCore.QRect(820, 630, 93, 28))
        self.save_btn.setObjectName("save_btn")

        self.retranslateUi(Form)
        self.v1_slider.sliderPressed.connect(Form.v1_stop)
        self.v2_slider.sliderPressed.connect(Form.v2_stop)
        self.final_slider.sliderPressed.connect(Form.all_stop)
        self.tongbu.pressed.connect(Form.tongbu_media)
        self.time_list.itemDoubleClicked['QListWidgetItem*'].connect(Form.go_active)
        self.v1_start_bnt.clicked.connect(Form.v1_start)
        self.v1_stop_bnt.clicked.connect(Form.v1_stop)
        self.v2_start_bnt.clicked.connect(Form.v1_start)
        self.v2_stop_bnt.clicked.connect(Form.v2_stop)
        self.final_start_bnt.clicked.connect(Form.all_start)
        self.final_stop_bnt.clicked.connect(Form.all_stop)
        self.bq_btn.clicked.connect(Form.label)
        self.save_btn.clicked.connect(Form.save_all)
        self.v1_slider.sliderMoved['int'].connect(Form.v1_set_time)
        self.v2_slider.sliderMoved['int'].connect(Form.v2_set_time)
        self.final_slider.sliderMoved['int'].connect(Form.all_set_time)
        self.final_slider.sliderPressed.connect(Form.all_stop)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tongbu.setText(_translate("Form", "同步"))
        self.time1.setText(_translate("Form", "TextLabel"))
        self.time2.setText(_translate("Form", "TextLabel"))
        self.v1_stop_bnt.setText(_translate("Form", "暂停"))
        self.v1_start_bnt.setText(_translate("Form", "开始"))
        self.v2_stop_bnt.setText(_translate("Form", "暂停"))
        self.v2_start_bnt.setText(_translate("Form", "开始"))
        self.final_start_bnt.setText(_translate("Form", "开始"))
        self.final_stop_bnt.setText(_translate("Form", "暂停"))
        self.final_time.setText(_translate("Form", "TextLabel"))
        self.bq_btn.setText(_translate("Form", "标签"))
        self.save_btn.setText(_translate("Form", "保存配置"))
