# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_pro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 434)
        self.video1_path = QtWidgets.QLineEdit(Form)
        self.video1_path.setGeometry(QtCore.QRect(60, 290, 341, 21))
        self.video1_path.setObjectName("video1_path")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(60, 320, 291, 16))
        self.label_9.setObjectName("label_9")
        self.v1_btn = QtWidgets.QPushButton(Form)
        self.v1_btn.setGeometry(QtCore.QRect(410, 290, 93, 28))
        self.v1_btn.setObjectName("v1_btn")
        self.v2_btn = QtWidgets.QPushButton(Form)
        self.v2_btn.setGeometry(QtCore.QRect(410, 340, 93, 28))
        self.v2_btn.setObjectName("v2_btn")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(60, 370, 291, 16))
        self.label_10.setObjectName("label_10")
        self.video2_path = QtWidgets.QLineEdit(Form)
        self.video2_path.setGeometry(QtCore.QRect(60, 340, 341, 21))
        self.video2_path.setObjectName("video2_path")
        self.create_btn = QtWidgets.QPushButton(Form)
        self.create_btn.setGeometry(QtCore.QRect(150, 400, 93, 28))
        self.create_btn.setObjectName("create_btn")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 20, 252, 245))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tea_grade = QtWidgets.QLineEdit(self.widget)
        self.tea_grade.setObjectName("tea_grade")
        self.gridLayout.addWidget(self.tea_grade, 5, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 2)
        self.tea_time = QtWidgets.QLineEdit(self.widget)
        self.tea_time.setObjectName("tea_time")
        self.gridLayout.addWidget(self.tea_time, 6, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.class_name = QtWidgets.QLineEdit(self.widget)
        self.class_name.setObjectName("class_name")
        self.gridLayout.addWidget(self.class_name, 1, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.grade = QtWidgets.QLineEdit(self.widget)
        self.grade.setObjectName("grade")
        self.gridLayout.addWidget(self.grade, 2, 3, 1, 1)
        self.tea_name = QtWidgets.QLineEdit(self.widget)
        self.tea_name.setObjectName("tea_name")
        self.gridLayout.addWidget(self.tea_name, 3, 3, 1, 1)
        self.tea_sex = QtWidgets.QLineEdit(self.widget)
        self.tea_sex.setObjectName("tea_sex")
        self.gridLayout.addWidget(self.tea_sex, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 2)
        self.pro_name = QtWidgets.QLineEdit(self.widget)
        self.pro_name.setObjectName("pro_name")
        self.gridLayout.addWidget(self.pro_name, 0, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.stu_name = QtWidgets.QLineEdit(self.widget)
        self.stu_name.setObjectName("stu_name")
        self.gridLayout_2.addWidget(self.stu_name, 1, 1, 1, 1)

        self.retranslateUi(Form)
        self.v1_btn.clicked.connect(Form.media_path1)
        self.v2_btn.clicked.connect(Form.media_path2)
        self.create_btn.clicked.connect(Form.create_csv)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "请直接输入视频1路径或点击按钮自动输入"))
        self.v1_btn.setText(_translate("Form", "视频1"))
        self.v2_btn.setText(_translate("Form", "视频2"))
        self.label_10.setText(_translate("Form", "请直接输入视频2路径或点击按钮自动输入"))
        self.create_btn.setText(_translate("Form", "创建"))
        self.label_6.setText(_translate("Form", "职称"))
        self.label_2.setText(_translate("Form", "课程名"))
        self.label_4.setText(_translate("Form", "教师姓名"))
        self.label.setText(_translate("Form", "项目名"))
        self.label_3.setText(_translate("Form", "课程年级"))
        self.label_5.setText(_translate("Form", "教师性别"))
        self.label_7.setText(_translate("Form", "教龄"))
        self.label_8.setText(_translate("Form", "学生人数"))
